#Init
install.packages("tidyverse")
install.packages('ggplot2')
install.packages('dplyr')
install.packages('tidyr')
install.packages('readr')
install.packages('cbsodataR')
install.packages('sf')

library(ggplot2)
library(dplyr)
library(tidyr)
library(readr)
library(tidyverse)
library(cbsodataR)
library(sf)

source("Gioravalav.R", echo = TRUE)
source("Spatial.R", echo = TRUE)
source("Subgroup.R", echo = TRUE)